parserOptions:
  ecmaVersion: 2018
plugins:
    - "react"
extends: [ 'airbnb-base', "plugin:react/recommended" ]
rules:
  semi: [ "error", "always"]
  quotes: [ "error", "single"]
  comma-spacing: [ "error", { before: false, after: true }]
  indent: [ 'error', 2 ]
  arrow-parens: [ "error", "always"]
  max-len: [ 'warn', 160 ]
  strict: off
  no-console: off
  no-unused-vars: off
  import/prefer-default-export: false
env:
  jest: true
  node: true
  es6: true
  browser: true
settings:
  react:
    version: "detect"